### ISSUE TITLE
The attribute name should say that it is a hint

### ISSUE THREAD

**Issue by smaug----** [dtapuska/enterkeyhint#3]
It could be like "actionhint"

**Comment by dtapuska** [comment]
I wanted inputmode- in the prefix so it is tied to the "inputmode". I'm happy with inputmode-action-hint.

**Comment by smaug----** [comment]
hmm, actually, perhaps I can live with the current name. The attribute can be interpreted also as a semantic thing, which some OSes just use as a button label effectively.
